algo = input('Digite algo:')
print('O tipo primitivo desse valor é:', type(algo))
print('Só tem espaços?', algo.isspace())
print('É um número?', algo.isnumeric())
print('É alfabético?', algo.isalpha())
print('É algo alphanumerico?', algo.isalnum())
print('Está em maisculo?', algo.isupper())
print('Está em minusculo?', algo.islower())
print('Está capitalizada?', algo.istitle())